const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 10.99,
      image: './images/item-1.jpeg',
      description: `Light, soft and fluffy with the perfect balance of sweet, salty and tang; you may not even want them smothered in syrup!`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      image: './images/item-2.jpeg',
      description: `Signature Homemade Beef Patty made from fresh lean ground beef daily that serve with aged cheddar cheese and 2 pcs of Bacon Strip with french fries`,
    },

    {
      id: 3,
      title: 'chicken shawarma',
      category: 'dinner',
      price: 16.99,
      image: './images/item-3.jpeg',
      description: `Marinated boneless chicken with our special seasoning, slowly roasted and sliced from our rotating spit. Served with Tahini sauce.`,
    },
    {
      id: 4,
      title: 'chocolate milkshake',
      category: 'shakes',
      price: 7.99,
      image: './images/item-4.jpeg',
      description: `chocolate milkshake is made with milk, chocolate syrup, and ice cream, so it's much richer, thicker, and frostier..`,
    },
    {
      id: 5,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      image: './images/item-5.jpeg',
      description: `This egg and baked beans is a basic breakfast and very simple but will satisfy your taste bud. You can easily transform this into a quick, simple, and hearty meal for breakfast! Yum!`,
    },
    {
      id: 6,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      image: './images/item-6.jpeg',
      description: `Beef Patty, Cheddar, Onion Chips,Tomato, Special Sauce, Mozzarella, Sunny-Side-Up Egg. `,
    },
    {
      id: 7,
      title: 'oreo dream',
      category: 'shakes',
      price: 7.99,
      image: './images/item-7.jpeg',
      description: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday.`,
    },
    {
      id: 8,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      image: './images/item-8.jpeg',
      description: `This high protein breakfast log has all the best parts of breakfast. Warm and fluffy eggs, crispy hash browns, cheesiness, and the unmistakable savoriness of bacon. `,
    },
    {
      id: 9,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      image: './images/item-9.jpeg',
      description: `Without referencing any grievances about the state of ground beef, the key to a perfect cheeseburger comes straight from the butcher. `,
    },
    {
      id: 10,
      title: 'Strawberry Shake',
      category: 'shakes',
      price: 7.99,
      image: './images/item-10.jpeg',
      description: `Strawberry Shake is made with creamy vanilla soft serve, blended with strawberry syrup and topped with whipped topping.`,
    },

    {
      id: 11,
      title: 'Three Eggs any Style With Your Choice',
      category: 'breakfast',
      price: 12.99,
      image: './images/item-11.jpeg',
      description: `Three eggs any style served with homefries, fruit, toast, and jam.`,
    },
    {
      id: 12,
      title: 'Tuna Melt Sandwich',
      category: 'lunch',
      price: 12.99,
      image: './images/item-12.jpeg',
      description: `Meet your ultimate sandwich. With just the right amount of crunch, melty cheddar cheese.`,
    },
    {
      id: 13,
      title: 'italian insalata mista',
      category: 'dinner',
      price: 7.99,
      image: './images/item-13.jpeg',
      description: `Organic baby greens salad, cherry tomato, red onion, mustard, evoo, white balsamic dressing, shaved reggiano cheese.`,
    },

    {
      id: 14,
      title: 'Beef-Shawarma-Platter',
      category: 'dinner',
      price: 18.99,
      image: './images/item-14.jpeg',
      description: `Marinated boneless beef with our special seasoning, slowly roasted and sliced from our rotating spit. Served with Tahini sauce.`,
    },
  ];

  export default menu;
  